Repository Real-Dev-Squad/website-status, pull requests merged in 2022-08, with the labels that each got.

#275 added progressbar to the status site cards
  src/components/tasks/card/card.module.scss
  src/components/tasks/card/index.tsx
Labels: UX

#285 upgraded the packages to latest versions available
  package.json
  public/mockServiceWorker.js
  yarn.lock
Labels: dependencies, enhancement

#288 Fix/progress bar fix
  src/components/tasks/card/index.tsx
Labels: enhancement
