Repository Real-Dev-Squad/website-status, pull requests merged in 2023-05, with the labels that each got.

#540 add pre commit hook to fix prettier issues before commit
  .husky/pre-commit
Labels: DX, enhancement, config

#525 add task progress page
  __tests__/Unit/Components/ProgressForm/ProgressForm.test.tsx
  __tests__/Unit/Components/ProgressForm/inputWithQuestions.test.tsx
  __tests__/Unit/pages/Progress/ProgressUpdatesPage.test.tsx
  src/components/ProgressForm/InputWithQuestions.tsx
  src/components/ProgressForm/ProgressForm.module.scss
  src/components/ProgressForm/ProgressForm.tsx
  src/components/ProgressForm/ProgressHeader.tsx
  src/components/ProgressForm/ProgressLayout.tsx
  src/components/taskDetails/index.tsx
  src/constants/ProgressUpdates.ts
  src/pages/progress/[id].tsx
  src/types/ProgressUpdates.d.ts
  src/utils/getLatestDate.ts
Labels: feature task

#515 mine task Api
  __tests__/Unit/hooks/useEditMode.test.tsx
  src/app/services/api.ts
  src/app/services/tasksApi.ts
  src/components/tasks/TasksContent.tsx
  src/components/tasks/card/index.tsx
  src/context/index.tsx
  src/hooks/useEditMode.ts
  src/pages/_app.tsx
  src/pages/challenges.tsx
  src/pages/mine.tsx
Labels: RTK

#545 move issues test from a seperate pages folder to common pages folder
  __tests__/Unit/pages/issues/Issues.test.tsx
Labels: refactor

#548 fix folder structure of pages
  src/pages/404/index.tsx
  src/pages/active/index.tsx
  src/pages/availability-panel/index.tsx
  src/pages/challenges/index.tsx
  src/pages/idle-users/index.tsx
  src/pages/issues/index.tsx
  src/pages/mine/index.tsx
  src/pages/openPRs/index.tsx
  src/pages/stale-pr/index.tsx
Labels: refactor

#552 move challenges mock from src to mocks
  __mocks__/db/challenges.ts
  src/mocks/challenges.json
Labels: refactor

#553 remove unused variables
  src/components/navBar/index.tsx
  src/components/tasks/card/TaskTagEdit.tsx
  src/components/tasks/card/index.tsx
  src/context/isUserAuthorized.tsx
Labels: refactor

#554 add tests for getLatestDate utility
  __tests__/Utils/getLatestDate.test.ts
Labels: tests

#551 remove console log and fix folder structure in unit tests
  __tests__/Unit/Components/Accordion/Accordion.test.tsx
  __tests__/Unit/Components/Navbar/Navbar.test.tsx
  __tests__/Unit/Components/TaskList/TaskList.test.tsx
  __tests__/Unit/hooks/taskTagAPI.test.tsx
  __tests__/Unit/hooks/userApi.test.tsx
Labels: refactor

#539 Fix: navbar hiding while fetching data
  __tests__/Unit/Components/Navbar/Navbar.test.tsx
  src/components/Layout/index.tsx
  src/components/navBar/index.tsx
Labels: bug

#563 Add RTK query and make task progress form work
  __tests__/Unit/Components/ProgressForm/ProgressForm.test.tsx
  src/app/services/progressesApi.ts
  src/components/ProgressForm/ProgressForm.tsx
Labels: feature task

#595 fixed task card long title (after adding feature-flag)
  src/components/tasks/card/ConditionalLinkWrapper.tsx
  src/components/tasks/card/card.module.scss
Labels: bug

#544 add dashboard page
  src/components/Dashboard/Dashboard.module.scss
  src/components/Dashboard/Searchbar.tsx
  src/pages/dashboard/index.tsx
  src/types/Searchbar.d.ts
  src/utils/splitNSearch.ts
Labels: feature task
