Repository Real-Dev-Squad/website-status, pull requests merged in 2023-07, with the labels that each got.

#679 chore: remove updateCardContent & use the RTK hook
  __mocks__/handlers/tasks.handler.js
  __tests__/Unit/Components/Tasks/TasksContent.test.tsx
  __tests__/Unit/Functions/updateTasksStatus.test.ts
  src/components/tasks/TabSection.tsx
  src/components/tasks/TaskList/TaskList.tsx
  src/components/tasks/TasksContent.tsx
  src/helperFunctions/updateCardContent.ts
  src/helperFunctions/updateTasksStatus.ts
Labels: refactor, RTK

#646 [Feature] : User should be able to update progress through progress bar slider
  src/components/tasks/card/ProgressBar.tsx
  src/components/tasks/card/ProgressIndicator.tsx
  src/components/tasks/card/ProgressSlider.tsx
  src/components/tasks/card/ProgressText.tsx
  src/components/tasks/card/card.module.scss
  src/components/tasks/card/index.tsx
  src/interfaces/task.type.ts
  src/utils/getPercentageOfDaysLeft.ts
  src/utils/handleProgressColor.ts
Labels: react

#750 sync dev to main
  __mocks__/db/progresses.ts
  __mocks__/handlers.ts
  __mocks__/handlers/progresses.handler.ts
  __tests__/Unit/Components/IdleUsers/Card.test.tsx
  __tests__/Unit/Components/Tasks/TasksContent.test.tsx
  __tests__/Unit/hooks/progressesApi.test.tsx
  __tests__/Unit/hooks/pullRequestsApi.test.tsx
  __tests__/Unit/utils/getActiveTab.test.ts
  src/app/services/api.ts
  src/app/services/progressesApi.ts
  src/components/ProgressForm/ProgressLayout.tsx
  src/components/idleUsers/card/index.tsx
  src/components/standup/index.tsx
  src/components/tasks/TasksContent.tsx
  src/constants/url.ts
  src/types/standup.type.ts
  src/utils/getActiveTab.ts
Labels: enhancement

#727 chore: cleanup old card design
  src/components/tasks/card/index.tsx
  src/constants/FeatureFlags.ts
Labels: refactor

#736 Fix edit button
  __tests__/Unit/Components/Tasks/Card.test.tsx
  __tests__/Unit/hooks/useEditMode.test.tsx
  src/components/tasks/TaskList/TaskList.tsx
  src/components/tasks/card/index.tsx
  src/hooks/useEditMode.ts
Labels: bug
