Repository Real-Dev-Squad/website-status, pull requests merged in 2023-06, with the labels that each got.

#522 Migrate Taskdetails API to RTK Query
  __mocks__/handlers/task-details.handler.ts
  __tests__/Unit/hooks/taskDetailsApi.test.tsx
  src/app/services/api.ts
  src/app/services/taskDetailsApi.ts
  src/components/taskDetails/index.tsx
  src/components/taskDetails/taskDetails.reducer.ts
  src/helperFunctions/convertTimeStamp.ts
  src/interfaces/taskDetails.type.ts
Labels: RTK

#599 Add dependsOn on taskDetails Page
  __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
  src/components/taskDetails/index.tsx
  src/components/taskDetails/task-details.module.scss
  src/interfaces/taskDetails.type.ts
Labels: feature task, tests

#618 Fix task content tab responsiveness
  src/styles/tasks.module.scss
Labels: UX

#628 fix styles of progress form to be responsive on small screens
  src/components/ProgressForm/ProgressForm.module.scss
  src/components/ProgressForm/ProgressHeader.tsx
  src/components/ProgressForm/ProgressLayout.tsx
Labels: UX, UI

#575 Adding User-name suggestions to AssignedTo field
  src/components/tasks/SuggestionBox/Loading.tsx
  src/components/tasks/SuggestionBox/SuggestionBox.tsx
  src/components/tasks/SuggestionBox/SuggestionList.tsx
  src/components/tasks/SuggestionBox/UserNotFound.tsx
  src/components/tasks/SuggestionBox/suggestion.module.scss
  src/components/tasks/card/card.module.scss
  src/components/tasks/card/index.tsx
  src/interfaces/suggestionBox.type.ts
Labels: UX, UI, react

#632 refactored code to trigger less re-rendering
  src/pages/issues/index.tsx
Labels: react

#655 Fix : inconsistency in the width of task-tabs and task-cards
  src/components/Header/Header.module.scss
  src/components/Tabs/Tabs.module.scss
  src/components/tasks/TaskList/TaskList.tsx
  src/components/tasks/card/card.module.scss
  src/styles/tasks.module.scss
Labels: UX

#643 Refactor: Migrate Tasks API calls to RTK query
  __mocks__/handlers/tasks.handler.js
  __tests__/Unit/Components/TaskList/TaskList.test.tsx
  __tests__/Unit/Components/Tasks/Card.test.tsx
  __tests__/Unit/hooks/tasksApi.test.tsx
  __tests__/Unit/hooks/useUpdateTask.test.tsx
  src/app/services/tasksApi.ts
  src/components/tasks/TaskList/TaskList.tsx
  src/components/tasks/TasksContent.tsx
  src/components/tasks/card/card.module.scss
  src/components/tasks/card/index.tsx
  src/hooks/useUpdateTask.ts
  src/interfaces/task.type.ts
  src/interfaces/taskItem.type.ts
Labels: RTK
